uv run --project envs/internvl python  test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  internvl  --model_id   OpenGVLab/InternVL3_5-8B-hf
uv run --project envs/internvl python  test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  internvl  --model_id   OpenGVLab/InternVL3-14B-hf
uv run --project envs/qwen3_5 python   test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  qwen3_5   --model_id   Qwen/Qwen3.5-9B
uv run --project envs/qwen3_5 python   test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  qwen3_5   --model_id   Qwen/Qwen3.5-4B
uv run --project envs/qwen python      test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  qwen3     --model_id   Qwen/Qwen3-VL-4B-Instruct
uv run --project envs/qwen python      test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  qwen3     --model_id   Qwen/Qwen3-VL-8B-Instruct
uv run --project envs/internvl python  test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  internvl  --model_id   OpenGVLab/InternVL3_5-8B-hf
uv run --project envs/eagle python     test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  eagle     --model_id   nvidia/Eagle2.5-8B
uv run --project envs/gpt python       test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gpt       --model_id   gpt-4o  --resize 512
uv run --project envs/gpt python       test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gpt       --model_id   gpt-5.1 --resize 512
uv run --project envs/gemini python    test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gemini    --model_id   gemini-2.5-flash
uv run --project envs/gemini python    test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gemini    --model_id   gemini-2.5-pro
uv run --project envs/gemini python    test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gemini    --model_id   gemini-3.1-pro-preview
uv run --project envs/gemini python    test.py  --task  spatio_temporal  --dataset_name  american_football  --split_num  0  --n_shot  0  --method uniform_sampling  --fps 1  --seed  42  --query_max_frames_num   120  --support_max_frames_num 120  --device  cuda:0  --model_name  gemini    --model_id   gemini-3.1-pro-preview
